// card owlCarousel
$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
      autoplay:true,
      loop:true,
      nav:false,
      responsive:{
        0:{
          items:1
        },
        700:{
          items:2
        },
        1000:{
          items:3
        },
      }
    });
  });